on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: message=$(cat /workspaces/git-pages-actions-playground/whatShouldTheCowSay.txt)
      - run: npx cowsay@1.6.0 "$message" > /workspaces/git-pages-actions-playground/lastCowMessage.txt
      - run: cat /workspaces/git-pages-actions-playground/index-top.html /workspaces/git-pages-actions-playground/lastCowMessage.txt /workspaces/git-pages-actions-playground/index-bottom.html > /workspaces/git-pages-actions-playground/docs/index.html
  
