on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: message=$(cat whatShouldTheCowSay.txt)
      - run: npx cowsay@1.6.0 "$message" > lastCowMessage.txt
      - run: cat index-top.html lastCowMessage.txt index-bottom.html > docs/index.html
  
